site_name: Oscloud Docs
site_description: 'Oscloud je váš osobní cloud a hosting webových aplikací.'
site_url: 'https://docs.oscloud.cz'
copyright: 'Copyright &copy; 2024 Oscloud CZ'
nav:
  - Úvodní stránka: 'index.md'
  - 'Registrace do OSCloud aplikací': Registrace do OSCloud aplikací.md
  - 'Webhosting a prémiové služby': Webhosting a prémiové služby.md
  - 'Podpora a kontakty':
    - 'Podpora': support.md
    - 'Kontaktujte nás': contact.md
  - 'Znalostní báze':
    - 'App': apps.md  
    - 'Certifikáty': certificates.md
    - 'Profil': profile.md
    - 'Security': security.md
    - 'Zálohy': backups.md
  - Aplikace:
    - 'BookStack': apps/bookstack.md
    - 'Castopod': apps/castopod.md
    - 'CryptPad': apps/cryptpad.md
    - 'Discourse': apps/discourse.md
    - 'Dokuwiki': apps/dokuwiki.md
    - 'FindMyDevice': apps/findmydevice.md
    - 'FreshRSS': apps/freshrss.md
    - 'Gitea': apps/gitea.md
    - 'GitHub Pages': apps/githubpages.md
    - 'HedgeDoc': apps/hedgedoc.md
    - 'Immich': apps/immich.md
    - 'Joplin Server': apps/joplin-server.md
    - 'LAMP': apps/lamp.md
    - 'Linkding': apps/linkding.md
    - 'Linkwarden': apps/linkwarden.md
    - 'Lychee': apps/lychee.md
    - 'Mastodon': apps/mastodon.md
    - 'Mealie': apps/mealie.md
    - 'Miniflux': apps/miniflux.md
    - 'MiroTalk': apps/mirotalk.md
    - 'Nextcloud': apps/nextcloud.md
    - 'NodeBB': apps/nodebb.md
    - 'Ntfy': apps/ntfy.md
    - 'PairDrop': apps/pairdrop.md
    - 'Peertube': apps/peertube.md
    - 'Piwigo': apps/piwigo.md
    - 'Pixelfed': apps/pixelfed.md
    - 'PrivateBin': apps/privatebin.md
    - 'Rallly': apps/rallly.md
    - 'Roundcube': apps/roundcube.md
    - 'SearXNG': apps/searxng.md
    - 'Surfer': apps/surfer.md
    - 'StirlingPDF': apps/stirling.md
    - 'TinyTinyRSS': apps/tinytinyrss.md
    - 'Umami': apps/umami.md
    - 'Vaultwarden': apps/vaultwarden.md
    - 'Vikunja': apps/vikunja.md
    - 'Wallabag': apps/wallabag.md
    - 'WordPress (Developer)': apps/wordpress-developer.md
    - 'WordPress (Managed)': apps/wordpress-managed.md

  - Ceny:
    - 'Jak nás podpořit': podporte-nas.md
  - Podmínky a soukromí:
    - 'Podmínky Oscloud CZ': podmínky Oscloud CZ.md
    - 'Zásady ochrany osobních údajů': privacy_policy.md
extra_css:
  - 'styly/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
theme:
  name: 'material'
  language: 'en'
  logo: 'img/logo.png'
  homepage: 'https://weboscloud.cz'
  favicon: 'img/favicon.ico'
  font: false
  features:
    - search.suggest
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'white'
      accent: 'light blue'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'black'
      accent: 'light blue'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  search:
    tokenizer: '[\s\-]+'
  social:
    - icon: fontawesome/brands/git
      link: 'https://git.arch-linux.cz/Oscloud'
    - icon: fontawesome/brands/mastodon
      link: 'https://mamutovo.cz/@oscloud'
    - icon: fontawesome/regular/comments
      link: 'https://matrix.to/#/!nnrBXdWbSiXkfiYtWR:mxchat.cz?via=mxchat.cz'
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta
  - pymdownx.magiclink
plugins:
  #  - social:
  #    cards: true
  - search:
      lang: en
